---
title: "part 2: preparing_DF"
author: "Mrinal Vashisth"
date: "3/9/2021"
output: html_document
---

```{r}
#load the dataframe

# /home/mrinalmanu/Desktop/analyse_pubmed_search_results/FINAL/topics/neuroscience_personality/NEU_PER_DF
# /home/mrinalmanu/Desktop/analyse_pubmed_search_results/FINAL/topics/neuroscience_identity/NEU_ID_DF
# /home/mrinalmanu/Desktop/analyse_pubmed_search_results/FINAL/topics/modelling_and_consciousness/MOD_CON_DF
# /home/mrinalmanu/Desktop/analyse_pubmed_search_results/FINAL/topics/digital_twin/DIG_T_DF

name_i <- "/home/mrinalmanu/Desktop/analyse_pubmed_search_results/FINAL/topics/modelling_and_consciousness/MOD_CON_DF"
name_f <- "/home/mrinalmanu/Desktop/analyse_pubmed_search_results/FINAL/topics/modelling_and_consciousness/ready_MOD_CON_DF"


```

```{r}

FinalDF <- read.csv(name_i)

subsetDF <- data.frame(FinalDF$doi, FinalDF$pmid, FinalDF$year, FinalDF$auth, FinalDF$number_of_authors, FinalDF$journal, FinalDF$title, FinalDF$abstract)

head(subsetDF)

#write.csv(subsetDF, file = "subsetDF", row.names = FALSE)


# subsetDF <- read_csv("Desktop/metagen_project/subsetDF")

# Two steps

# first: seperate for ; character
# second: explode for | character
library(splitstackshape)

new <- cSplit(subsetDF, "FinalDF.auth", ";", "long")

ready_DF <- cSplit(new, "FinalDF.auth", "|", "wide")

write.csv(ready_DF, file = name_f, row.names = FALSE)

```


=